# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  こちらの issues は、直近のアクティビティが見られないため、一週間後に close します。
  問題がある場合は、pinned ラベルを追加するか、更新をお願いいたします。
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false